app/src/main/java/com/marverenic/music/PlayerService.java, app/src/main/java/com/marverenic/music/activity/BaseActivity.java, app/src/main/res/drawable/ic_pause_36dp.xml, app/src/main/res/drawable/ic_play_arrow_36dp.xml, app/src/main/res/drawable/ic_skip_next_36dp.xml, app/src/main/res/drawable/ic_skip_previous_36dp.xml, app/src/main/res/layout-v21/miniplayer.xml, app/src/main/res/layout-v21/notification.xml, app/src/main/res/layout-v21/notification_expanded.xml, app/src/main/res/layout/miniplayer.xml, app/src/main/res/layout/notification.xml, app/src/main/res/layout/notification_expanded.xml
- Shrank icons used in the miniplayer and notification
=> Resized small player control buttons

app/build.gradle, app/proguard-rules.pro, app/src/main/java/com/marverenic/music/JockeyApplication.java, app/src/main/java/com/marverenic/music/activity/instance/ArtistActivity.java, app/src/main/java/com/marverenic/music/instances/viewholder/AlbumViewHolder.java, app/src/main/res/layout/activity_about.xml, app/src/main/res/layout/instance_artist_suggested.xml, app/src/main/res/values/strings.xml
- Better image caching
- Removed Circular Image View dependency
- Updated about page
- Fixed Last.fm "read more" truncation bug and crash
=> Switched from Picasso to Glide

app/src/main/java/com/marverenic/music/player/MusicPlayer.java
Single clicking the inline remote button will toggle between playing and paused states as it did previously. Double clicking the inline remote button will skip to the next song, and triple clicking will skip to the previous song or restart the current song (as defined in `MusicPlayer.skipPrevious()`).
=> Handle double and triple clicks of inline remote differently

app/src/main/java/com/marverenic/music/activity/LibraryActivity.java, app/src/main/java/com/marverenic/music/activity/NowPlayingActivity.java, app/src/main/java/com/marverenic/music/dialog/AppendPlaylistDialogFragment.java, app/src/main/java/com/marverenic/music/dialog/CreatePlaylistDialogFragment.java, app/src/main/java/com/marverenic/music/viewmodel/AlbumViewModel.java, app/src/main/java/com/marverenic/music/viewmodel/ArtistViewModel.java, app/src/main/java/com/marverenic/music/viewmodel/GenreViewModel.java, app/src/main/java/com/marverenic/music/viewmodel/NowPlayingControllerViewModel.java, app/src/main/java/com/marverenic/music/viewmodel/QueueSongViewModel.java, app/src/main/java/com/marverenic/music/viewmodel/SongViewModel.java
Reimplements functionality that was removed after switching to DialogFragments to edit and create playlists.
=> Show confirmation Snackbars after creating and editing playlists

app/src/main/java/com/marverenic/music/activity/LibraryActivity.java, app/src/main/java/com/marverenic/music/activity/instance/AlbumActivity.java, app/src/main/java/com/marverenic/music/activity/instance/ArtistActivity.java, app/src/main/java/com/marverenic/music/activity/instance/AutoPlaylistActivity.java, app/src/main/java/com/marverenic/music/activity/instance/GenreActivity.java, app/src/main/java/com/marverenic/music/activity/instance/PlaylistActivity.java, app/src/main/java/com/marverenic/music/data/inject/JockeyGraph.java, app/src/main/java/com/marverenic/music/data/store/LocalMusicStore.java, app/src/main/java/com/marverenic/music/data/store/LocalPlaylistStore.java, app/src/main/java/com/marverenic/music/fragments/AlbumFragment.java, app/src/main/java/com/marverenic/music/fragments/ArtistFragment.java, app/src/main/java/com/marverenic/music/fragments/GenreFragment.java, app/src/main/java/com/marverenic/music/fragments/PlaylistFragment.java, app/src/main/java/com/marverenic/music/fragments/QueueFragment.java, app/src/main/java/com/marverenic/music/fragments/SongFragment.java, app/src/main/java/com/marverenic/music/instances/section/LibraryEmptyState.java
Resolves various inconsistencies when refreshing the library where the new data would not appear on the UI. This also causes empty states to refresh playlists with the rest of the library.
=> Fix refresh button behavior

app/src/main/java/com/marverenic/music/activity/instance/AlbumActivity.java, app/src/main/java/com/marverenic/music/instances/Song.java
Resolves an issue where songs on the album page were sorted by song name instead of by track number
=> Fix incorrect sorting on album page

app/src/main/java/com/marverenic/music/viewmodel/QueueSongViewModel.java
After a song is removed from the now playing queue, a confirmation snackbar will be displayed with the option to undo the song deletion.
=> Show confirmation snackbar when removing songs from the queue

app/src/main/java/com/marverenic/music/fragments/GenreFragment.java, app/src/main/res/values/empty.xml
Differentiates the empty state on the genre page between whether the user has no music or no genres
=> Make genre empty state more descriptive

app/src/main/res/layout-sw600dp-land/activity_now_playing.xml, app/src/main/res/layout/view_now_playing_control_panel.xml, app/src/main/res/layout/view_now_playing_controls.xml, app/src/main/res/values-sw600dp-land/dimens.xml, app/src/main/res/values-sw600dp/dimens.xml, app/src/main/res/values-sw700dp-land/dimens.xml, app/src/main/res/values-sw700dp/dimens.xml, app/src/main/res/values/dimens.xml
Fixes various issues with Multi-Window configurations causing awkward layout configurations that made Jockey's now playing page unusable for certain actions. See individual commit descriptions for more information.
=> Fix various Multi-Window issues

app/src/main/java/com/marverenic/music/data/store/MediaStoreUtil.java
Resolves an issue where granting storage permissions would not trigger a full library refresh. Only songs would be reloaded. This was caused by the MediaStoreUtil only processing one permission request at a time, and immediately denying other requests before the user could respond to the dialog. The MediaStoreUtil now remembers the last result of the permission request and returns that instead.
=> Fix library not fully loading after granting storage permissions

.travis.yml, app/build.gradle, app/src/main/res/values/strings.xml, build.gradle, gradle.properties, heterogeneousadapter/build.gradle, seekarc/build.gradle
Updates the support library to version 25.1.0, build tools to 25.0.2, and the gradle build tools to version 2.2.3.
=> Update support library and build tools

app/src/main/java/com/marverenic/music/fragments/QueueFragment.java, app/src/main/java/com/marverenic/music/player/MusicPlayer.java, app/src/main/java/com/marverenic/music/viewmodel/MiniplayerViewModel.java, app/src/main/res/values/strings.xml
Fixes minor bugs and inconsistencies introduced in version 2.0
=> Fix minor bugs

app/src/main/java/com/marverenic/music/activity/BaseActivity.java, app/src/main/java/com/marverenic/music/activity/MainActivity.java, app/src/main/java/com/marverenic/music/activity/NowPlayingActivity.java, app/src/main/java/com/marverenic/music/activity/instance/ArtistActivity.java, app/src/main/java/com/marverenic/music/data/inject/ContextModule.java, app/src/main/java/com/marverenic/music/data/inject/MediaStoreModule.java, app/src/main/java/com/marverenic/music/data/store/ImmutablePreferenceStore.java, app/src/main/java/com/marverenic/music/data/store/LocalMusicStore.java, app/src/main/java/com/marverenic/music/data/store/PreferenceStore.java, app/src/main/java/com/marverenic/music/data/store/PresetThemeStore.java, app/src/main/java/com/marverenic/music/data/store/ReadOnlyPreferenceStore.java, app/src/main/java/com/marverenic/music/data/store/RemotePreferenceStore.java, app/src/main/java/com/marverenic/music/data/store/SharedPreferenceStore.java, app/src/main/java/com/marverenic/music/fragments/DirectoryListFragment.java, app/src/main/java/com/marverenic/music/fragments/EqualizerFragment.java, app/src/main/java/com/marverenic/music/fragments/PreferenceFragment.java, app/src/main/java/com/marverenic/music/player/MusicPlayer.java, app/src/main/java/com/marverenic/music/player/PlayerController.java, app/src/main/java/com/marverenic/music/utils/compat/JockeyPreferencesCompat.java, app/src/main/java/com/marverenic/music/viewmodel/SongViewModel.java
Makes all PreferenceStore implementation names consistent
=> Rename PreferencesStore to PreferenceStore

app/src/main/java/com/marverenic/music/adapter/PlaylistSongSection.java, app/src/main/java/com/marverenic/music/adapter/SongSection.java, app/src/main/java/com/marverenic/music/player/MockPlayerController.java, app/src/main/java/com/marverenic/music/viewmodel/PlaylistSongViewModel.java, app/src/main/java/com/marverenic/music/viewmodel/QueueSongViewModel.java, app/src/main/java/com/marverenic/music/viewmodel/SongViewModel.java, app/src/main/res/layout/instance_song.xml, app/src/main/res/layout/instance_song_drag.xml, app/src/test/java/com/marverenic/music/viewmodel/SongViewModelTest.java
=> Show now playing indicator on songs in lists outside of the now playing page

app/src/main/java/com/marverenic/music/data/store/LocalPlaylistStore.java, app/src/main/java/com/marverenic/music/viewmodel/QueueSongViewModel.java
Fixes an issue where adding a song in the queue to a playlist would append the entire queue, not just the song that was selected.
=> Fix queue songs not being appended to playlists correctly

app/src/main/java/com/marverenic/music/activity/BaseLibraryActivity.java, app/src/main/java/com/marverenic/music/viewmodel/SongViewModel.java
=> Open sliding now playing page when changing songs

app/src/main/java/com/marverenic/music/player/ServicePlayerController.java
Fixes a caught exception where a null queue could cause queue subscriptions to terminate early
=> Fix NPE thrown by Observables

.travis.yml, app/build.gradle, app/src/main/java/com/marverenic/music/adapter/ArtistBioSingleton.java, app/src/main/res/layout/instance_album.xml, app/src/main/res/layout/instance_artist.xml, app/src/main/res/layout/instance_artist_bio.xml, app/src/main/res/layout/instance_artist_suggested.xml, app/src/main/res/layout/instance_genre.xml, app/src/main/res/layout/instance_playlist.xml, app/src/main/res/layout/instance_song.xml, app/src/main/res/layout/instance_song_drag.xml, app/src/main/res/layout/instance_song_queue.xml, app/src/main/res/layout/view_now_playing_control_panel.xml, app/src/main/res/layout/view_now_playing_controls.xml, app/src/main/res/layout/view_now_playing_details.xml, app/src/main/res/layout/view_now_playing_scrubber.xml, app/src/main/res/values-sw600dp/dimens.xml, app/src/main/res/values-sw700dp-land/dimens.xml, app/src/main/res/values-sw700dp/dimens.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Replaces common list item layouts and layouts on the now playing page with ConstraintLayout implementations. This replaces many nested view hierarchies with flat layouts, which reduces the amount of time spent laying out views. This performance gain is mostly negligible in practice (especially on newer devices), but can still reduce the number of layout passes by a power of 2 for nested RelativeLayouts.
=> Convert layouts to ConstraintLayout

app/src/main/java/com/marverenic/music/data/store/ImmutablePreferenceStore.java, app/src/main/java/com/marverenic/music/data/store/ReadOnlyPreferenceStore.java, app/src/main/java/com/marverenic/music/data/store/SharedPreferenceStore.java, app/src/main/java/com/marverenic/music/fragments/PreferenceFragment.java, app/src/main/java/com/marverenic/music/player/MusicPlayer.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs.xml
This preference is disabled by default. Closes #51.
=> Add a setting to resume music when headphones are connected

app/src/main/java/com/marverenic/music/fragments/NowPlayingFragment.java, app/src/main/java/com/marverenic/music/player/MockPlayerController.java, app/src/main/java/com/marverenic/music/player/MusicPlayer.java, app/src/main/java/com/marverenic/music/player/PlayerController.java, app/src/main/java/com/marverenic/music/player/QueuedExoPlayer.java, app/src/main/java/com/marverenic/music/player/ServicePlayerController.java
=> Fix incorrect repeat and shuffle icon states on the Now Playing page

app/src/main/java/com/marverenic/music/player/QueuedExoPlayer.java
Resolves an issue introduced in c9a61239870b929ad296ee1a25b7c72a76b7a1eb and closes #269.
=> Fix repeat one behavior

app/src/main/java/com/marverenic/music/activity/BaseActivity.java, app/src/main/java/com/marverenic/music/data/store/PresetThemeStore.java, app/src/main/java/com/marverenic/music/data/store/ThemeStore.java, app/src/main/res/values-night/bools.xml, app/src/main/res/values/bools.xml
Resolves an issue where changes to the background theme would not be applied to activities in the background. This is caused both when the user changes the background theme between light and dark as well as when night mode is automatically changed.
=> Fix background theme not being applied to activities in the background

app/src/main/java/com/marverenic/music/adapter/ArtistSection.java, app/src/main/java/com/marverenic/music/adapter/GenreSection.java, app/src/main/java/com/marverenic/music/adapter/HeterogeneousFastScrollAdapter.java, app/src/main/java/com/marverenic/music/adapter/HomogeneousFastScrollAdapter.java, app/src/main/java/com/marverenic/music/adapter/PlaylistSection.java, app/src/main/java/com/marverenic/music/adapter/SpacerSingleton.java, app/src/main/java/com/marverenic/music/fragments/AlbumFragment.java
=> Fix fast scrollbars only appearing on songs tab of library

app/src/main/res/values/strings.xml
=> Fix missing word in legal disclaimer

app/src/main/java/com/marverenic/music/data/inject/JockeyGraph.java, app/src/main/java/com/marverenic/music/ui/library/LibraryActivity.java, app/src/main/java/com/marverenic/music/ui/library/recentlyadded/RecentlyAddedFragment.java, app/src/main/java/com/marverenic/music/ui/library/recentlyadded/RecentlyAddedViewModel.java, app/src/main/res/drawable/ic_new_24dp.xml, app/src/main/res/layout/fragment_recently_added.xml, app/src/main/res/menu/activity_library_drawer.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values/strings.xml
=> Create Recently Added page

app/src/main/java/com/marverenic/music/ui/library/artist/contents/ArtistBioSingleton.java, app/src/main/res/layout/instance_artist_bio.xml
=> Fix Last.fm button overlapping bio text

app/src/main/java/com/marverenic/music/ui/library/album/contents/AlbumFragment.java
Fixes a regression on the album page.
=> Sort songs by track number on album page

app/src/main/java/com/marverenic/music/ui/library/LibraryFragment.java, app/src/main/java/com/marverenic/music/ui/library/browse/MusicBrowserFragment.java, app/src/main/java/com/marverenic/music/ui/library/recentlyadded/RecentlyAddedFragment.java, app/src/main/java/com/marverenic/music/ui/library/recentlyadded/RecentlyAddedViewModel.java, app/src/main/res/layout/fragment_music_browser.xml, app/src/main/res/layout/fragment_recently_added.xml
=> Fix library page losing some of its state on configuration changes

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/marverenic/music/player/MusicPlayer.java
=> Bump version and prepare for 3.0 beta 1 release

app/src/main/AndroidManifest.xml, app/src/main/java/com/marverenic/music/data/inject/JockeyGraph.java, app/src/main/java/com/marverenic/music/ui/browse/BreadCrumbView.java, app/src/main/java/com/marverenic/music/ui/browse/FileBrowserEmptyState.java, app/src/main/java/com/marverenic/music/ui/browse/FileSection.java, app/src/main/java/com/marverenic/music/ui/browse/FileViewModel.java, app/src/main/java/com/marverenic/music/ui/browse/FolderSection.java, app/src/main/java/com/marverenic/music/ui/browse/FolderViewModel.java, app/src/main/java/com/marverenic/music/ui/browse/MusicBrowserActivity.java, app/src/main/java/com/marverenic/music/ui/browse/MusicBrowserFragment.java, app/src/main/java/com/marverenic/music/ui/browse/MusicBrowserViewModel.java, app/src/main/java/com/marverenic/music/ui/browse/ThumbnailLoader.java, app/src/main/java/com/marverenic/music/ui/library/LibraryActivity.java, app/src/main/java/com/marverenic/music/ui/library/playlist/contents/PlaylistSongItemViewModel.java, app/src/main/java/com/marverenic/music/ui/library/song/SongItemViewModel.java, app/src/main/java/com/marverenic/music/ui/nowplaying/NowPlayingControllerViewModel.java, app/src/main/java/com/marverenic/music/ui/nowplaying/QueueSongItemViewModel.java, app/src/main/res/layout/fragment_music_browser.xml, app/src/main/res/layout/instance_empty.xml, app/src/main/res/layout/instance_file.xml, app/src/main/res/layout/instance_folder.xml, app/src/main/res/menu/instance_song.xml, app/src/main/res/menu/instance_song_now_playing.xml, app/src/main/res/menu/instance_song_now_playing_remote.xml, app/src/main/res/menu/instance_song_playlist.xml, app/src/main/res/menu/instance_song_queue.xml, app/src/main/res/menu/instance_song_queue_remote.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values/strings.xml
=> Add menu item to show songs in the music browser

app/src/main/AndroidManifest.xml, app/src/main/java/com/marverenic/music/ui/nowplaying/NowPlayingFragment.java, app/src/main/java/com/marverenic/music/ui/settings/EqualizerActivity.java, app/src/main/java/com/marverenic/music/ui/settings/EqualizerFragment.java, app/src/main/res/menu/activity_now_playing.xml
=> Add shortcut to the equalizer on the now playing page

app/build.gradle, app/src/main/java/com/marverenic/music/ui/common/playlist/CreatePlaylistDialogFragment.java, app/src/main/java/com/marverenic/music/ui/library/playlist/contents/edit/AutoPlaylistEditFragment.java, app/src/main/java/com/marverenic/music/ui/library/playlist/contents/edit/AutoPlaylistEditViewModel.java, app/src/main/java/com/marverenic/music/ui/library/playlist/contents/edit/RuleHeaderSingleton.java, app/src/main/java/com/marverenic/music/ui/library/playlist/contents/edit/RuleHeaderViewModel.java, app/src/main/java/com/marverenic/music/ui/library/playlist/contents/edit/RuleSection.java, app/src/main/java/com/marverenic/music/ui/library/playlist/contents/edit/RuleViewModel.java, app/src/main/java/com/marverenic/music/utils/UriUtils.java, app/src/main/java/com/marverenic/music/view/AnchoredImageView.java, app/src/main/res/layout/instance_album.xml, app/src/main/res/layout/instance_artist.xml, app/src/main/res/layout/instance_directory.xml, app/src/main/res/layout/instance_genre.xml, app/src/main/res/layout/instance_playlist.xml, app/src/main/res/layout/instance_song.xml, app/src/main/res/layout/instance_song_drag.xml, app/src/main/res/layout/instance_song_queue.xml, build.gradle, exoplayer-flac/build.gradle, gradle/wrapper/gradle-wrapper.properties, seekarc/build.gradle
- Fixes an issue where Jockey would crash if a `content` URI can't be resolved to a local path
- Fixes NPEs when creating or editing an Auto Playlist
- Fixes an issue where the name of a playlist would be lost in the create playlist dialog when the device is rotated
- Fixes an issue where opening a menu in a list would sometimes cause the list to scroll (Closes #296)
=> Fix various minor bugs

app/src/main/java/com/marverenic/music/data/api/JockeyStatusApi.java, app/src/main/java/com/marverenic/music/data/api/JockeyStatusService.java, app/src/main/java/com/marverenic/music/data/api/PrivacyPolicyMetadata.java, app/src/main/java/com/marverenic/music/data/inject/ContextModule.java, app/src/main/java/com/marverenic/music/data/inject/DemoComponent.java, app/src/main/java/com/marverenic/music/data/inject/JockeyComponent.java, app/src/main/java/com/marverenic/music/data/inject/JockeyStatusModule.java, app/src/main/java/com/marverenic/music/data/inject/TestComponent.java, app/src/main/java/com/marverenic/music/data/manager/PrivacyPolicyManager.java, app/src/main/java/com/marverenic/music/data/store/SharedPreferenceStore.java, app/src/main/java/com/marverenic/music/ui/BaseActivity.java, app/src/main/java/com/marverenic/music/ui/about/AboutActivity.java, app/src/main/java/com/marverenic/music/utils/OkHttpUtils.java, app/src/main/res/layout/activity_about.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values/strings.xml
This merges the work from #374 into master
=> Merge privacy policy changes into 3.0 release branch

app/build.gradle
Completes [#166859258](https://www.pivotaltracker.com/story/show/166859258).
=> Bump version to 3.0 RC 1

app/src/main/java/com/marverenic/music/player/ServicePlayerController.java
Completes [#167117963](https://www.pivotaltracker.com/story/show/167117963).
The bindings system used by `ServicePlayerController` had a subtle issue related to states. It assumed that the service was always started by the time that a disconnect was required. This may not be the case, because the service will never be started if storage permission isn't granted, and it also might not take into account a scenario where a consumer requests a binding and then immediately disposes of it. This causes an `IllegalArgumentException` in some scenarios (see the testing steps for reproduction steps, and the ticket above for the full stacktrace).
The contract of these bindings has not changed, but `ServicePlayerController` now takes these other states into account and is more careful about how it …
=> Improve service binding state management
