marverenic/Jockey

- app/src/main/java/com/marverenic/music/data/store/LocalMusicStore.java
- app/src/main/java/com/marverenic/music/data/store/LocalPlaylistStore.java
Refactors MusicStore and PlaylistStore implementation to perform library loading computations in the background with RxJava. Currently, this only affects the list of all playlists, songs, artists, albums, and genres – not actions getting song group contents or finding entries by ID.
> Load library contents asynchronously

- app/src/main/java/com/marverenic/music/player/ManagedMediaPlayer.java
- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
- app/src/main/java/com/marverenic/music/player/QueuedMediaPlayer.java
- heterogeneousadapter/src/main/java/com/marverenic/heterogeneousadapter/DragDropAdapter.java
Fixes an issue where reordering the items in the queue would seemingly not have any affect – tapping on the reordered song would change the queue index to the song's previous index. This was caused by the ViewModels associated with each itemView not updating their index when an item in a list was reorganized. To solve this issue, `DragDropAdapter` now calls `notifyDataSetChange()` after each drop to make sure that ViewModels are updated  with correct data.
> Fix unexpected behavior when reordering queue items

- app/src/main/java/com/marverenic/music/player/PlayerService.java
Changes the notification behavior to be dismissable while playback is paused – dropping the requirement that the app had to be closed (i.e. not in the task stack).
> Allow the player service to be closed on Lollipop and higher while the app is running

- app/src/main/java/com/marverenic/music/activity/instance/ArtistActivity.java
Resolves an issue where the loading spinner would continue to display after an artist failed to load (either because it is not in the Last.fm database, or because a network error occurred), as well as a non-fatal NPE.
**Reproduction Steps:**
- Open the artist page for an artist not in the Last.fm database
- The loading spinner will never disappear
Also:
- Open an artist page while connected to a network with no internet access
- The loading spinner will never disappear
**Expected behavior:**
- If the artist is not in Last.fm, or there is an error loading the data, the loading spinner should disappear.
> Fix NPE & loading spinner incorrectly showing

- app/src/main/java/com/marverenic/music/dialog/DurationPickerDialogFragment.java
This fixes an issue where recreating a DurationPickerDialogFragment would not persist the previously selected duration and would reset to 0.
> Persist DurationPickerDialog state across rotations

- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
Resolves an issue where removing a song from the queue when shuffle is enabled would keep the song in the queue after disabling shuffle.
> Fix shuffled and non-shuffled queues becoming out of sync

- app/src/main/java/com/marverenic/music/viewmodel/NowPlayingControllerViewModel.java
Reproduction steps:
- Play a song in Jockey
- Run `adb shell am stopservice com.marverenic.music.debug/com.marverenic.music.player.PlayerService` in a terminal
- Open the now playing page
Expected Behavior:
- When the service restarts, the seekbar will be enabled
> Fix seekbar on now playing page becomming incorrectly disabled

- app/build.gradle
- build.gradle
As of version 2.2 of the gradle build tools, annotation proccessors are supported in gradle without the need for android-apt
> Replace apt with annotationProcessor

- app/src/main/java/com/marverenic/music/fragments/QueueFragment.java
- app/src/main/java/com/marverenic/music/instances/section/EditableSongSection.java
- app/src/main/java/com/marverenic/music/instances/section/QueueSection.java
- app/src/main/java/com/marverenic/music/instances/section/SpacerSingleton.java
- app/src/main/java/com/marverenic/music/player/PlayerController.java
- app/src/main/java/com/marverenic/music/view/DragBackgroundDecoration.java
- app/src/main/java/com/marverenic/music/view/QueueAnimator.java
- app/src/main/java/com/marverenic/music/view/SnappingScroller.java
Resolves numerous defects related to the queue list on the now playing page including:
- After upgrading the RecyclerView support library, the current track is never scrolled to when the song changes
- Skipping to the next song may incorrectly trigger the removal animation
- Skipping to the previous song may incorrectly trigger the add animation
> Fix scrolling behavior on now playing queue

- app/src/main/java/com/marverenic/music/activity/NowPlayingActivity.java
When the now playing activity is orphaned on the back stack (i.e. was opened from the notification when none of Jockey's activities are in the background) the up button now navigates to the library activity (this does not affect back button behavior, which will still just pop the back stack).
> Fix up button behavior on the now playing page

- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
- app/src/main/java/com/marverenic/music/player/QueuedExoPlayer.java
Whenever there is an update to the queue (i.e. reordered/added/deleted items, or changes to shuffle and repeat settings) the ExoPlayer timeline has to be rebuilt. This takes time, and would cause an audible gap in playback if it is done immediately. To avoid this, the preparation step is deferred until there is already going to be a gap in playback (i.e. when music is played, paused, seeked through, skipped, or finished). This will temporarily prevent gapless playback if the user edits the queue, but shouldn't be noticeable in practice since most users won't be constantly altering the queue.
> Defer queue updates until the current song finishes

- app/src/main/aidl/com/marverenic/music/IPlayerService.aidl
- app/src/main/java/com/marverenic/music/activity/NowPlayingActivity.java
- app/src/main/java/com/marverenic/music/activity/SearchActivity.java
- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
- app/src/main/java/com/marverenic/music/player/PlayerController.java
- app/src/main/java/com/marverenic/music/player/PlayerService.java
- app/src/main/java/com/marverenic/music/player/QueuedExoPlayer.java
- app/src/main/java/com/marverenic/music/player/QueuedMediaPlayer.java
- app/src/main/java/com/marverenic/music/viewmodel/QueueSongViewModel.java
- app/src/main/java/com/marverenic/music/viewmodel/SongViewModel.java
Resolves an issue where changing the queue would not correctly update playback.
**Reproduction steps:**
- Play music a song from the "Songs" tab of the library
- Play the same song from somewhere else (e.g. the album page or a playlist)
**Expected behavior:**
- The chosen song should play, and the queue should update with the songs from the page that was selected
**Actual behavior:**
- The queue would be changed, but a different song may start playing
> Fix incorrect playback after changing the queue

- app/src/main/java/com/marverenic/music/player/PlayerService.java
Fixes a potential crash where the service binder may be returned to the main thread before the service has finished its call to `onCreate()`. Previously, this would cause accesses and commands to the service to throw NPEs to the main thread. This implementation simply drops all incoming commands if the service has not finished its `onCreate()` call before data is accessed.
> Fix potential startup crash

- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
Resolves an issue where audio focus would never be regained after it was lost (either fully or transiently). This allows music to resume automatically after a phone call ends. Closes #43.
> Fix AudioFocus not being regained correctly

- app/src/main/java/com/marverenic/music/player/PlayerService.java
- app/src/main/java/com/marverenic/music/player/ServicePlayerController.java
- app/src/main/java/com/marverenic/music/widget/BaseWidget.java
Fixes a number of issues related to restarting the service. The main issue fixed is the service notification reappearing after stopping the service and removing Jockey from the list of recent apps. One minor behavior change associated with this is that if music is paused and Jockey is removed from the list of recent apps, then the service will be stopped and its notification will always be removed.
This also fixes a bug introduced in #192 on KitKat where the service would be killed and not restarted after pausing music when the app was not in the list of recent apps.
> Fix service restart behavior

- app/src/main/java/com/marverenic/music/player/QueuedExoPlayer.java
Fixes an issue where seek position appears invalid after a cold start. This is because ExoPlayer does not resolve a duration until a song has finished loading. The current workaround is to check if ExoPlayer returns an invalid duration. If it does return an invalid duration, it returns the last valid duration. If there isn't one, it defaults to the duration embedded in the song object. This may be inaccurate since it's pulled from the MediaStore, but should work most of the time.
> Fix duration initializing to 0 on cold start

- app/src/main/java/com/marverenic/music/player/PlayerService.java
Fixes a bug where closing and restarting Jockey would not allow the UI to control music playback. To reproduce, start Jockey, play music, remove the app from the recent tasks, and stop the service by dismissing it. Then, restart Jockey. The service will reappear and can play music, but the UI cannot be used to control playback.
> Fix service not binding to app after restart

- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
- app/src/main/java/com/marverenic/music/player/QueuedExoPlayer.java
Resolves an issue where queue list modifications would not be reflected in music playback because of an issue where the queue reference was shared between the MusicPlayer and QueuedExoPlayer classes. This is avoided by making immutable copies of the queue.
**Reproduction steps:**
- Start playback of a new queue
- Add another song the queue (this can be any song, but it's more noticeable if it's not the next song in the queue)
- Skip to the song that was added (either with the skip button or by selecting it on the queue page)
**Expected behavior:**
- The song that was enqueued should start playing
**Actual behavior:**
- The UI shows that the enqueued song is playing, but music playback acts like the song was never enqueued
> Fix appending to the queue not invalidating the ExoPlayer Timeline

- app/src/main/java/com/marverenic/music/utils/compat/JockeyPreferencesCompat.java
**Reproduction steps:**
- Install Jockey 2.0
- Change the color theme to anything but the default
- Close Jockey and update it to 2.1
- Launch Jockey 2.1. The color theme will be correct
- Open the settings page. The accent color theme will reset to cyan
> Fix incorrect accent color after upgrading from Jockey 2.0

- app/src/main/java/com/marverenic/music/data/store/LocalPlaylistStore.java
This fixes an issue where editing a playlist would not refresh the data shown in playlist activities in the background until they are reopened.
> Keep playlist observables up-to-date

- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
**Reproduction steps:**
- Play music with shuffle enabled
- Close and restart Jockey
- Navigate to any part of the library, and select a new song to start playing
**Expected behavior:**
- The selected song should start playing and the queue should be changed
**Actual behavior:**
- The queue will not be changed, and playback will be unaffected
> Fix queue not changing with shuffle enabled after restarting Jockey

- app/src/main/java/com/marverenic/music/player/PlayerService.java
Fixes an issue where changes to the app's AudioFocus could cause the service notification to reappear. Closes #224.
**Reproduction Steps:**
- Start Jockey and play music
- Pause music and dismiss the notification, but leave Jockey running in the background
- Perform an action that removes audio focus from Jockey (e.g. accepting a phone call)
**Expected Behavior:**
- The notification should remain hidden until music is played again
**Actual Behavior:**
- The notification will reappear
> Fix notification reappearing after AudioFocus changes

- .travis.yml
This should improve the speed of Travis Builds by only compiling and testing release builds of Jockey
> Reduce Travis CI Build Time

- app/build.gradle
Bumps the version code by 1 to differentiate between builds with and without the patch in #243.
> Bump version code

- app/src/main/java/com/marverenic/music/utils/Util.java
MediaMetadataRetriever throws a RuntimeException (not a descendant) when an error occurrs. This commit catches these errors and returns null when an error is thrown to prevent the player service from crashing.
> Catch errors from MediaMetadataRetriever

- app/src/main/java/com/marverenic/music/player/QueuedExoPlayer.java
Fixes an IndexOutOfBoundsException thrown when building a repeat-one timeline when the queue is empty.
> Fix crash when starting Jockey with repeat 1 and an empty queue

- app/src/main/java/com/marverenic/music/view/FABMenu.java
- app/src/main/java/com/marverenic/music/view/GestureView.java
- app/src/main/java/com/marverenic/music/viewmodel/NowPlayingArtworkViewModel.java
Modifies animation-dependent code to allow gestures to be started before the previous gesture has finished animating out. This also fixes an issue where the FAB on the library page would be hidden on the playlists tab after rapidly switching between pages.
> Improve animations & support faster gestures

- app/src/main/java/com/marverenic/music/fragments/QueueFragment.java
Resolves an issue where changing the queue would not scroll the Now Playing queue to the correct song if the Now Playing page was in the background
> Fix queue scroll position not updating

- circle.yml
Previously, all CircleCI configuration was done through the web console. This PR moves the current build configuration into a circle.yml config file.
> Add CircleCI configuration to repo

- app/src/main/java/com/marverenic/music/data/store/LocalMusicStore.java
When I include folder `/sdcard/foo` and `/sdcard/bar`, Jockey's query command for album be like:
```sql
album_id = 123 AND _data LIKE '/sdcard/foo/%' OR _data LIKE '/sdcard/bar/%'
```
But It should be:
```sql
album_id = 123 AND (_data LIKE '/sdcard/foo/%' OR _data LIKE '/sdcard/bar/%')
```
> Correct include/exclude folder query

- app/proguard-rules.pro
Resolves a defect in release builds where gestures would not animate. It seems like the `@Keep` annotation isn't working correctly right now.
> Prevent proguard from stripping code with Keep annotations

- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
- app/src/main/java/com/marverenic/music/player/ServicePlayerController.java
- app/src/main/java/com/marverenic/music/utils/Util.java
This replaces the old implementation for loading full-size album artwork in favor of one that uses RxJava with Glide. In addition to being easier to move off the main thread, this should also be a bit safer in how it loads images and also allows for more complicated rules to find artwork. For example, in addition to using `MediaMetadataRetriever`, this implementation will then try to fallback to a `cover.jpg` or `folder.jpg` image if available, and then on a thumbnail in the MediaStore before falling back to the default placeholder image.
> Reimplement full size album artwork loading

- app/src/main/aidl/com/marverenic/music/IPlayerService.aidl
- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
- app/src/main/java/com/marverenic/music/player/PlayerService.java
- app/src/main/java/com/marverenic/music/player/ServicePlayerController.java
All IPC now happens off the main thread. Additionally, values are predicted to instantly update the UI where possible, instead of waiting both the initial request and IPC read for the player state to come in. These two improvements significantly reduce UI stuttering when performing long operations like changing the queue with several hundreds of songs.
> Improve UI responsiveness when performing IPC

- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
- app/src/main/java/com/marverenic/music/player/PlayerService.java
- app/src/main/java/com/marverenic/music/player/extensions/MusicPlayerExtension.java
- app/src/main/java/com/marverenic/music/player/extensions/scrobbler/ScrobblerExtension.java
- app/src/main/java/com/marverenic/music/player/extensions/scrobbler/SlsMessenger.java
Fixes #326 and also adds scrobbling support to other supported services
(eg. libre.fm).
The reasoning behind not implementing the interaction with the service(s) in this app are described [here](https://github.com/marverenic/Jockey/issues/6#issuecomment-358376949).
Here's the link to [SLS API description](https://github.com/tgwizard/sls/blob/master/Developer's%20API.md).
> Add scrobbling support via SLS

- app/src/main/java/com/marverenic/music/JockeyApplication.java
- app/src/main/java/com/marverenic/music/player/MockPlayerController.java
- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
- app/src/main/java/com/marverenic/music/player/PlayerController.java
- app/src/main/java/com/marverenic/music/player/PlayerService.java
- app/src/main/java/com/marverenic/music/player/ServicePlayerController.java
- app/src/main/java/com/marverenic/music/player/browser/JockeyBrowserService.java
- app/src/main/java/com/marverenic/music/ui/BaseActivity.java
- app/src/main/java/com/marverenic/music/utils/RxProperty.java
- app/src/main/java/com/marverenic/music/widget/BaseWidget.java
Android O introduces a number of new [background execution limits for services](https://developer.android.com/about/versions/oreo/background#services). In particular, there is a restriction that a background application cannot start services (if it attempts to, an `IllegalStateException` will be thrown). One notable exception to this is that bound services are exempt from these limits.
In several cases, Jockey needs to be able to start the playback service from a stopped state. The most notable is for Android Auto, where the screen may not even be on when the service needs to start. This wouldn't normally be an issue because Jockey does use a bound service, except that the mechanism for starting the service was pretty hacky. It was previously started as a regular service, and then …
> Fix service launching behavior for Oreo

- app/src/main/java/com/marverenic/music/data/annotations/StartPage.java
- app/src/main/java/com/marverenic/music/ui/SingleFragmentActivity.java
- app/src/main/java/com/marverenic/music/ui/library/LibraryActivity.java
- app/src/main/java/com/marverenic/music/ui/library/LibraryViewModel.java
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This PR updates the setting for the default page in Jockey to be set to the recently added or the music browser page in addition to any of the tabs in the library page. If the library page is opened with either of these initial pages set, the library page will be opened to the songs tabs.
> Allow recently added and browser page to be the default page

- app/src/main/java/com/marverenic/music/widget/BaseWidget.java
- app/src/main/java/com/marverenic/music/widget/CompactWidget.java
- app/src/main/java/com/marverenic/music/widget/SquareWidget.java
- app/src/main/java/com/marverenic/music/widget/WideWidget.java
The previous implementation Jockey's widgets has a race condition: the player controller's binding is released before data could be fetched from the remote service. This causes the remote binding to be released and the widget to never update unless another component was bound to the service.
The fix for this issue is to wait until widgets' subscriptions return a value before unbinding from the remote service.
> Fix widgets not updating when Jockey is not in the foreground

- app/src/main/java/com/marverenic/music/data/store/PresetThemeStore.java
- app/src/main/java/com/marverenic/music/utils/Util.java
Completes [#155288425](https://www.pivotaltracker.com/story/show/155288425).
On pre-O devices, the icon shown on the overview page would automatically be updated to match the app theme. This was broken on Oreo devices with the introduction of adaptive icons. This PR matches this behavior on newer devices.
Before | After
|:-:|:-:|
> Match task icon with app theme on O+ devices

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
This adds a set of issue templates and PR templates to improve consistency. GitHub will pre-populate these templates for new PR's and issues.
> Create issue templates

- app/src/main/java/com/marverenic/music/utils/OkHttpUtils.java
Completes [#164159454](https://www.pivotaltracker.com/story/show/164159454).
Fixes a crash where builds that use Proguard would fail to start on older devices that require an SSL workaround to check for privacy policy changes.
Run a release build of the app on a device running Android 4.1-4.4.
> Fix launch crash in release builds on pre-L devices

- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
- app/src/main/java/com/marverenic/music/player/PlayerService.java
- app/src/main/java/com/marverenic/music/player/extensions/scrobbler/SlsMessenger.java
- app/src/main/java/com/marverenic/music/ui/nowplaying/MiniplayerViewModel.java
This fixes [#162533648](https://www.pivotaltracker.com/story/show/162533648) as well as a few other miscellaneous issues related to communication between the player service and UI procress.
In order of commit, the following changes have been made.
There was a logic issue that would cause the playback notification to appear when Jockey was not in the foreground or had not yet begun to play music in this app session. This should reduce the frequency of unexpected playback notifications.
On devices running Android Oreo and higher, there are changes to background execution limits that may cause the playback notification to get stuck in the playing state, leaving an playback notification that could not be dismissed.
To reproduce, play music without opening the app. You can do this by using a …
> Fix various issues related to music player service

- app/src/main/java/com/marverenic/music/player/ServicePlayerController.java
- app/src/main/java/com/marverenic/music/ui/search/SearchFragment.java
- app/src/main/java/com/marverenic/music/ui/search/SearchViewModel.java
- build.gradle
Fixes [#164840198](https://www.pivotaltracker.com/story/show/164840198) and [#164840086](https://www.pivotaltracker.com/story/show/164840086).
This PR fixes two UI-related crashes reported in Crashlytics. Stacktraces can be found in the Pivotal Tracker links above.
I don't have solid reproduction steps here, but it appears that calling `mShuffleMode.lastValue()` in `ServicePlayerController` isn't a reliable way to determine whether shuffle is enabled or not. There is now a fallback value that will be used.
This can be reproduced by attempting to play music from a search query intent. An easy way to do this is to ask the Google Assistant to play music in your library -- you'll immediately see an NPE. This was happening because the hosting activity was attempting to interact with …
> Fix major UI-crashes from Crashlytics

- app/src/main/res/menu/activity_now_playing_repeat.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values/strings.xml
Completes [#164747532](https://www.pivotaltracker.com/story/show/164747532).
The repeat mode menu was previously using hardcoded strings in the menu resource. This PR introduces new string resources to localize that menu.
| Before | After |
|:------:|:-----:|
> Add translations for repeat mode names

- app/src/main/java/com/marverenic/music/player/ServicePlayerController.java
Fixes [#165954849](https://www.pivotaltracker.com/story/show/165954849).
This PR fixes an issue where setting the queue as an unmodifiable list (like the list of all songs) might cause an UnsupportedOperationException to be thrown if another component got a reference to the list and attempted to modify it.
1. Open app as usual
2. Make sure shuffle is disabled
3. Choose any song from Songs tab
4. Open the queue and try to rearrange any of the songs in the list
5. The app will crash with `UnsupportedOperationException`
> Fix potential UnsupportedOperationException

- app/build.gradle
- app/src/main/java/com/marverenic/music/player/MusicPlayer.java
- build.gradle
- exoplayer-flac/build.gradle
Completes [#166105021](https://www.pivotaltracker.com/story/show/166105021).
The logic used to generate a sliding window of the current queue for the MediaSession breaks for long queues if the index of the current song is less than 120 songs away from the end of the queue. This PR revisits the logic used to generate this window, which should make it more robust.
1. Enqueue a large number of songs (~500 is a good number)
2. Start playing the second-to-last song in the queue
3. Press the skip button
**Expected behavior:** The last song in the queue begins to play
**Actual behavior:** The music player service crashes
> Fix potential IndexOutOfBoundsException

- app/src/main/java/com/marverenic/music/player/extensions/persistence/PersistenceExtension.java
Completes [#166859204](https://www.pivotaltracker.com/story/show/166859204).
This fixes an issue where the player service would crash when restoring its state on launch if there are songs that could not be found in the saved state.
- Begin playing music
- Skip to the last track in the queue
- Close Jockey
- Delete the file for the previously playing song from the device entirely
- Restart Jockey
**Expected Behavior:**
- Jockey should restore as much of the queue as possible
**Actual Behavior:**
- The player service crashes on startup
**Stacktrace:**
```
Caused by java.lang.IllegalArgumentException: index must be smaller than the queue size (1)
at com.marverenic.music.player.QueuedExoPlayer.setQueue(QueuedExoPlayer.java:235)
at com.marverenic.music.player.MusicPlayer.setBackingQueue(MusicPl …
```
> Fix IndexOutOfBoundsException on service start

- .circleci/config.yml
- .gitignore
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/marverenic/music/ui/common/ShuffleAllSection.java
- app/src/main/java/com/marverenic/music/ui/common/SpacerSingleton.java
- app/src/main/java/com/marverenic/music/ui/library/artist/ArtistSection.java
- app/src/main/java/com/marverenic/music/ui/library/genre/GenreSection.java
- app/src/main/java/com/marverenic/music/ui/library/playlist/PlaylistSection.java
- app/src/main/java/com/marverenic/music/ui/library/song/SongSection.java
- app/src/main/java/com/marverenic/music/view/HeterogeneousFastScrollAdapter.java
- app/src/main/java/com/marverenic/music/view/MeasurableSection.java
- app/src/main/res/drawable/inset_top_shadow.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/marverenic/music/utils/UtilTest.java
- build.gradle
Completes [#160705000](https://www.pivotaltracker.com/story/show/160705000).
This bumps the targetSdk version to API level 28, to add support for Android Pie. There were a number of dependency changes that were required to satisfy Gradle (some of which were caused by conflicting dependency versions). 
This would require a full regression test, but because this isn't going to be part of the initial 3.0 release, there is going to be a lot of time to test the implications of this library bump. Everything seems to be working as-is, but there are known changes to the preferences support library that are affecting its appearance. This work is tracked in [#144999499](https://www.pivotaltracker.com/story/show/144999499).
> Bump targetSdk to API level 28

- app/src/main/java/com/marverenic/music/ui/library/song/SongSection.java
Completes [#166892253](https://www.pivotaltracker.com/story/show/166892253).
Verify that dragging the scrollbar on the songs tab of the library page shows the first letter of the song title, ignoring prefixes that are overlooked in the sorting order.
> Fix incorrect fast scroll label

- app/src/main/res/layout/fragment_library_page.xml
Fixes issue when scrollbar thumb was nearly invisible due to its color
Pivotal tracker link : https://www.pivotaltracker.com/story/show/167117735
Change to dark mode in settings and observe the scrollbar thumb is visible in main screen fragments.
> Fixes scrollbar thumb color issue
